package importyandex

import (
	"encoding/json"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
	"time"
)

// ==========================================
// LABEL CLASSIFICATION — single source of truth
// ==========================================

// knownNonFolder — the ONLY place that defines what is NOT an IMAP folder.
// CATEGORY_* is handled via prefix check in isNonFolder(), not hardcoded here.
var knownNonFolder = map[string]bool{
	"INBOX":     true, // fallback, excluded from priority
	"UNREAD":    true, // flag → \Seen
	"STARRED":   true, // flag → \Flagged
	"IMPORTANT": true, // flag, not a folder
	"CHAT":      true, // Gmail Chat label, not an IMAP folder
}

// isNonFolder checks if a label ID is something other than an IMAP folder.
// CATEGORY_* always maps to INBOX (autogenerated Google tabs, not folders).
// Prefix check means new CATEGORY_XXX is handled automatically.
func isNonFolder(id string) bool {
	if knownNonFolder[id] {
		return true
	}
	return strings.HasPrefix(id, "CATEGORY_")
}

// systemFolders — the ONLY table mapping system labels → IMAP folders.
// Order = priority (TRASH beats SPAM beats SENT etc.)
var systemFolders = [][2]string{
	{"TRASH", "Trash"},
	{"SPAM", "Spam"},
	{"SENT", "Sent"},
	{"DRAFT", "Drafts"},
}

// russianToIMAPFolder — reverse mapping: Russian name → IMAP folder.
var russianToIMAPFolder = map[string]string{
	"Удалённые":    "Trash",
	"Спам":         "Spam",
	"Отправленные": "Sent",
	"Черновики":    "Drafts",
	"Входящие":     "INBOX",
}

// ==========================================
// RESOLVE — deterministic label → folder mapping
// ==========================================

// ResolveFolder returns exactly one target IMAP folder for a message.
// Priority: system folders > user labels > INBOX.
func ResolveFolder(labelIDs []string, labelNames map[string]string) string {
	set := toSet(labelIDs)

	// 1. System folders by priority
	for _, rule := range systemFolders {
		if _, ok := set[rule[0]]; ok {
			return rule[1]
		}
	}

	// 2. User labels (Label_xxx) — excluding isNonFolder
	var userLabels []string
	for id := range set {
		if !isNonFolder(id) {
			userLabels = append(userLabels, id)
		}
	}
	sort.Strings(userLabels) // deterministic
	if len(userLabels) > 0 {
		return resolveUserLabel(userLabels[0], labelNames)
	}

	// 3. Fallback
	return "INBOX"
}

// resolveUserLabel resolves a user label ID to an IMAP folder name.
func resolveUserLabel(labelID string, labelNames map[string]string) string {
	name, ok := labelNames[labelID]
	if !ok {
		return "INBOX"
	}
	if strings.HasPrefix(name, "[Imap]/") {
		name = strings.TrimPrefix(name, "[Imap]/")
		if mapped, ok := russianToIMAPFolder[name]; ok {
			return mapped
		}
		return sanitizeFolderName(name)
	}
	return sanitizeFolderName(name)
}

// sanitizeFolderName removes characters that are invalid in IMAP folder names.
// IMAP uses quotes as delimiters, so quotes inside names break the protocol.
// Also removes backslashes and parentheses which can cause issues.
func sanitizeFolderName(name string) string {
	name = strings.ReplaceAll(name, `"`, "")
	name = strings.ReplaceAll(name, `\`, "")
	name = strings.ReplaceAll(name, "(", "")
	name = strings.ReplaceAll(name, ")", "")
	name = strings.TrimSpace(name)
	if name == "" {
		return "INBOX"
	}
	return name
}

// ResolveFlags returns IMAP flags for a message based on Gmail labels.
// UNREAD absent → \Seen (read); STARRED present → \Flagged.
func ResolveFlags(labelIDs []string) []string {
	idSet := make(map[string]struct{}, len(labelIDs))
	for _, id := range labelIDs {
		idSet[id] = struct{}{}
	}

	var flags []string

	// UNREAD absent → message was read → \Seen
	if _, ok := idSet["UNREAD"]; !ok {
		flags = append(flags, `\Seen`)
	}

	// STARRED present → \Flagged
	if _, ok := idSet["STARRED"]; ok {
		flags = append(flags, `\Flagged`)
	}

	return flags
}

// toSet converts a slice to a map for O(1) lookup.
func toSet(ids []string) map[string]struct{} {
	set := make(map[string]struct{}, len(ids))
	for _, id := range ids {
		set[id] = struct{}{}
	}
	return set
}

// ==========================================
// TYPES
// ==========================================

// Letter — email with label binding from migration labels file.
type Letter struct {
	Path       string            // S3 path
	MsgID      string            // Gmail msg_id
	LabelIDs   []string          // raw label IDs from file
	LabelNames map[string]string // label_id → human-readable name (from UserLabels)
}

// UserLabels — data from migration_labels*.json for one user.
type UserLabels struct {
	Messages   map[string][]string `json:"messages"`
	LabelNames map[string]string   `json:"label_names"`
	Done       bool                `json:"done"`
}

// LabelsFile — full migration_labels*.json: email → UserLabels.
type LabelsFile map[string]*UserLabels

// ==========================================
// PARSING
// ==========================================

// ParseLabelsFile parses migration_labels*.json.
func ParseLabelsFile(path string) (LabelsFile, error) {
	start := time.Now()
	log.Printf("[DEBUG] [LABELS] чтение файла лейблов: %s", path)
	raw, err := os.ReadFile(path)
	if err != nil {
		log.Printf("[ERROR] [LABELS] чтение %s за %s: %v", path, time.Since(start), err)
		return nil, fmt.Errorf("read %s: %w", path, err)
	}
	log.Printf("[DEBUG] [LABELS] файл прочитан: %d bytes за %s", len(raw), time.Since(start))
	return ParseLabelsJSON(raw)
}

// ParseLabelsJSON parses JSON labels from bytes (for tests).
func ParseLabelsJSON(data []byte) (LabelsFile, error) {
	log.Printf("[DEBUG] [LABELS] парсинг JSON лейблов (%d bytes)", len(data))
	var file LabelsFile
	if err := json.Unmarshal(data, &file); err != nil {
		log.Printf("[ERROR] [LABELS] парсинг JSON: %v", err)
		return nil, fmt.Errorf("parse labels: %w", err)
	}
	log.Printf("[INFO] [LABELS] JSON распарсен: %d юзеров в файле лейблов", len(file))
	for email, ul := range file {
		log.Printf("[DEBUG] [LABELS] юзер %s: %d messages, %d labelNames, done=%v",
			email, len(ul.Messages), len(ul.LabelNames), ul.Done)
	}
	return file, nil
}

// ==========================================
// MATCHING
// ==========================================

// MatchLetters matches S3 emails with labels from file.
// Returns Letters for emails with found labels and warnings for skipped ones.
func MatchLetters(email string, emails []EmailMeta, labels LabelsFile) ([]Letter, []string) {
	start := time.Now()
	log.Printf("[DEBUG] [LABELS] %s: MatchLetters — %d emails из S3", email, len(emails))
	userLabels, ok := labels[email]
	if !ok {
		log.Printf("[WARN] [LABELS] %s: нет записи в файле лейблов, все %d писем пропущены", email, len(emails))
		var warnings []string
		for _, e := range emails {
			warnings = append(warnings, fmt.Sprintf("[WARN] [LABELS] %s: нет записи в файле лейблов, пропуск %s", email, e.Key))
		}
		return nil, warnings
	}
	log.Printf("[DEBUG] [LABELS] %s: найден в файле лейблов: %d messages, %d labelNames",
		email, len(userLabels.Messages), len(userLabels.LabelNames))

	var letters []Letter
	var warnings []string
	for _, e := range emails {
		letterLabels, ok := userLabels.Messages[e.MessageID]
		if !ok {
			warnings = append(warnings, fmt.Sprintf("[WARN] [LABELS] %s: лейблы не найдены для %s, пропуск", email, e.Key))
			log.Printf("[DEBUG] [LABELS] %s: лейблы не найдены для msgID=%s key=%s", email, e.MessageID, e.Key)
			continue
		}
		letters = append(letters, Letter{
			Path:       e.Key,
			MsgID:      e.MessageID,
			LabelIDs:   letterLabels,
			LabelNames: userLabels.LabelNames,
		})
	}

	log.Printf("[INFO] [LABELS] %s: %d/%d писем с лейблами, %d пропущено (за %s)",
		email, len(letters), len(emails), len(warnings), time.Since(start))
	for _, w := range warnings {
		log.Println(w)
	}

	return letters, warnings
}
